apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels: { app: backend }
  template:
    metadata:
      labels: { app: backend }
    spec:
      containers:
      - name: backend
        image: backend:demo
        imagePullPolicy: IfNotPresent
        env:
        - name: PGHOST
          value: "postgres-service"
        - name: PGUSER
          value: "postgres"
        - name: PGPASSWORD
          value: "postgrespw"
        - name: PGDATABASE
          value: "demo"
        ports:
        - containerPort: 3000